name: Scheduled Health Check

on:
  [push]

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://bloglist-ci-cd-23i4.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false

      - name: Notify success
        uses: stegzilla/discord-notify@v4
        if: success()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health check passed!
          message: 'The health check for the bloglist application succeeded.'

      - name: Notify failure
        uses: stegzilla/discord-notify@v4
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health check failed!
          message: 'The health check for the bloglist application failed.'
